// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package db

import (
	"context"
	"time"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO incident_attachments (
    incident_id, filename_original, filename_stored,
    mime_type, size_bytes, sha256
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, incident_id, filename_original, filename_stored,
          mime_type, size_bytes, sha256, created_at,
          uploaded_to_jira_at, purged_at
`

type CreateAttachmentParams struct {
	IncidentID       string
	FilenameOriginal string
	FilenameStored   string
	MimeType         string
	SizeBytes        int64
	Sha256           string
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (IncidentAttachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.IncidentID,
		arg.FilenameOriginal,
		arg.FilenameStored,
		arg.MimeType,
		arg.SizeBytes,
		arg.Sha256,
	)
	var i IncidentAttachment
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.FilenameOriginal,
		&i.FilenameStored,
		&i.MimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
		&i.UploadedToJiraAt,
		&i.PurgedAt,
	)
	return i, err
}

const listAttachmentsByIncident = `-- name: ListAttachmentsByIncident :many
SELECT id, incident_id, filename_original, filename_stored,
       mime_type, size_bytes, sha256, created_at,
       uploaded_to_jira_at, purged_at
FROM incident_attachments
WHERE incident_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAttachmentsByIncident(ctx context.Context, incidentID string) ([]IncidentAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByIncident, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentAttachment{}
	for rows.Next() {
		var i IncidentAttachment
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.FilenameOriginal,
			&i.FilenameStored,
			&i.MimeType,
			&i.SizeBytes,
			&i.Sha256,
			&i.CreatedAt,
			&i.UploadedToJiraAt,
			&i.PurgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsPendingJiraUpload = `-- name: ListAttachmentsPendingJiraUpload :many
SELECT a.id, a.incident_id, a.filename_original, a.filename_stored,
       a.mime_type, a.size_bytes, a.sha256, a.created_at,
       a.uploaded_to_jira_at, a.purged_at,
       i.jira_issue_key
FROM incident_attachments a
JOIN incidents i ON i.id = a.incident_id
WHERE a.uploaded_to_jira_at IS NULL
  AND a.purged_at IS NULL
  AND i.jira_sync = TRUE
  AND i.jira_issue_key IS NOT NULL
ORDER BY a.created_at ASC
LIMIT $1
`

// ListAttachmentsPendingJiraUploadRow es el tipo combinado del JOIN:
// la fila de incident_attachments más jira_issue_key del incidente padre.
type ListAttachmentsPendingJiraUploadRow struct {
	ID               string
	IncidentID       string
	FilenameOriginal string
	FilenameStored   string
	MimeType         string
	SizeBytes        int64
	Sha256           string
	CreatedAt        time.Time
	UploadedToJiraAt *time.Time
	PurgedAt         *time.Time
	JiraIssueKey     *string
}

func (q *Queries) ListAttachmentsPendingJiraUpload(ctx context.Context, limit int32) ([]ListAttachmentsPendingJiraUploadRow, error) {
	rows, err := q.db.Query(ctx, listAttachmentsPendingJiraUpload, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttachmentsPendingJiraUploadRow{}
	for rows.Next() {
		var i ListAttachmentsPendingJiraUploadRow
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.FilenameOriginal,
			&i.FilenameStored,
			&i.MimeType,
			&i.SizeBytes,
			&i.Sha256,
			&i.CreatedAt,
			&i.UploadedToJiraAt,
			&i.PurgedAt,
			&i.JiraIssueKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttachmentUploadedToJira = `-- name: MarkAttachmentUploadedToJira :exec
UPDATE incident_attachments
SET uploaded_to_jira_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkAttachmentUploadedToJira(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markAttachmentUploadedToJira, id)
	return err
}

const listAttachmentsPurgeable = `-- name: ListAttachmentsPurgeable :many
SELECT id, incident_id, filename_original, filename_stored,
       mime_type, size_bytes, sha256, created_at,
       uploaded_to_jira_at, purged_at
FROM incident_attachments
WHERE purged_at IS NULL
  AND created_at < $1
ORDER BY created_at ASC
LIMIT $2
`

type ListAttachmentsPurgeableParams struct {
	CreatedAt time.Time
	Limit     int32
}

func (q *Queries) ListAttachmentsPurgeable(ctx context.Context, arg ListAttachmentsPurgeableParams) ([]IncidentAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsPurgeable, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentAttachment{}
	for rows.Next() {
		var i IncidentAttachment
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.FilenameOriginal,
			&i.FilenameStored,
			&i.MimeType,
			&i.SizeBytes,
			&i.Sha256,
			&i.CreatedAt,
			&i.UploadedToJiraAt,
			&i.PurgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttachmentPurged = `-- name: MarkAttachmentPurged :exec
UPDATE incident_attachments
SET purged_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkAttachmentPurged(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markAttachmentPurged, id)
	return err
}
