// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Incident struct {
	ID              string
	Title           string
	Description     string
	Author          string
	CreatedAt       time.Time
	JiraSync        bool
	JiraIssueKey    *string
	SyncRetries     int32
	LastSyncAttempt *time.Time
	Metadata        []byte
}

type IncidentAttachment struct {
	ID                string
	IncidentID        string
	FilenameOriginal  string
	FilenameStored    string
	MimeType          string
	SizeBytes         int64
	Sha256            string
	CreatedAt         time.Time
	UploadedToJiraAt  *time.Time
	PurgedAt          *time.Time
}
