// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"
)

type Querier interface {
	ClaimPendingSync(ctx context.Context, arg ClaimPendingSyncParams) ([]Incident, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (IncidentAttachment, error)
	CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error)
	ListAttachmentsByIncident(ctx context.Context, incidentID string) ([]IncidentAttachment, error)
	ListAttachmentsPendingJiraUpload(ctx context.Context, limit int32) ([]ListAttachmentsPendingJiraUploadRow, error)
	ListAttachmentsPurgeable(ctx context.Context, arg ListAttachmentsPurgeableParams) ([]IncidentAttachment, error)
	MarkAttachmentPurged(ctx context.Context, id string) error
	MarkAttachmentUploadedToJira(ctx context.Context, id string) error
	MarkIncidentSyncFailed(ctx context.Context, id string) error
	MarkIncidentSynced(ctx context.Context, arg MarkIncidentSyncedParams) error
	PurgeOldMetadata(ctx context.Context, createdAt time.Time) (int64, error)
}

var _ Querier = (*Queries)(nil)
