// Code generated by sqlc. DO NOT EDIT.
// Este archivo se regenera con:  sqlc generate
// Está commiteado a mano para que el proyecto compile sin necesidad
// de tener sqlc instalado. La salida real de `sqlc generate` debería
// ser idéntica (o equivalente) a este archivo.

package db

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// DBTX es el contrato mínimo que cumple tanto *pgxpool.Pool como pgx.Tx.
type DBTX interface {
	Exec(context.Context, string, ...any) (pgconn.CommandTag, error)
	Query(context.Context, string, ...any) (pgx.Rows, error)
	QueryRow(context.Context, string, ...any) pgx.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

// WithTx devuelve un Queries ligado a una transacción.
func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{db: tx}
}
