// Code generated by sqlc. DO NOT EDIT.
// source: db/queries/incidents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// ----------------- CreateIncident -----------------

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (title, description, author, jira_sync, metadata)
VALUES ($1, $2, $3, FALSE, $4)
RETURNING id, title, description, author, created_at, jira_sync, jira_issue_key, sync_retries, last_sync_attempt, metadata
`

type CreateIncidentParams struct {
	Title       string
	Description string
	Author      string
	Metadata    []byte
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.Title, arg.Description, arg.Author, arg.Metadata,
	)
	var i Incident
	err := row.Scan(
		&i.ID, &i.Title, &i.Description, &i.Author, &i.CreatedAt,
		&i.JiraSync, &i.JiraIssueKey, &i.SyncRetries, &i.LastSyncAttempt, &i.Metadata,
	)
	return i, err
}

// ----------------- MarkIncidentSynced -----------------

const markIncidentSynced = `-- name: MarkIncidentSynced :exec
UPDATE incidents
SET jira_sync = TRUE,
    jira_issue_key = $2,
    last_sync_attempt = NOW()
WHERE id = $1
`

type MarkIncidentSyncedParams struct {
	ID           string
	JiraIssueKey pgtype.Text
}

func (q *Queries) MarkIncidentSynced(ctx context.Context, arg MarkIncidentSyncedParams) error {
	_, err := q.db.Exec(ctx, markIncidentSynced, arg.ID, arg.JiraIssueKey)
	return err
}

// ----------------- MarkIncidentSyncFailed -----------------

const markIncidentSyncFailed = `-- name: MarkIncidentSyncFailed :exec
UPDATE incidents
SET sync_retries = sync_retries + 1,
    last_sync_attempt = NOW()
WHERE id = $1
`

func (q *Queries) MarkIncidentSyncFailed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markIncidentSyncFailed, id)
	return err
}

// ----------------- ListPendingSync -----------------

const listPendingSync = `-- name: ListPendingSync :many
SELECT id, title, description, author, created_at, jira_sync, jira_issue_key, sync_retries, last_sync_attempt, metadata
FROM incidents
WHERE jira_sync = FALSE
  AND sync_retries < $1
ORDER BY created_at ASC
LIMIT $2
`

type ListPendingSyncParams struct {
	MaxRetries int32
	Limit      int32
}

func (q *Queries) ListPendingSync(ctx context.Context, arg ListPendingSyncParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listPendingSync, arg.MaxRetries, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID, &i.Title, &i.Description, &i.Author, &i.CreatedAt,
			&i.JiraSync, &i.JiraIssueKey, &i.SyncRetries, &i.LastSyncAttempt, &i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
