// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// Incident es el modelo de la capa de persistencia (1:1 con la tabla).
// Distinto del modelo de dominio (models.Incident) y del DTO (dto.IncidentResponse).
type Incident struct {
	ID              string             // UUID (override -> string)
	Title           string
	Description     string
	Author          string
	CreatedAt       time.Time          // NOT NULL
	JiraSync        bool
	JiraIssueKey    pgtype.Text        // nullable
	SyncRetries     int32
	LastSyncAttempt pgtype.Timestamptz // nullable
	Metadata        []byte             // JSONB
}
