// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error)
	ListPendingSync(ctx context.Context, arg ListPendingSyncParams) ([]Incident, error)
	MarkIncidentSyncFailed(ctx context.Context, id string) error
	MarkIncidentSynced(ctx context.Context, arg MarkIncidentSyncedParams) error
}

var _ Querier = (*Queries)(nil)
